
const ELASTICSEARCH_URL = process.env.ELASTICSEARCH_URL
const ELASTICSEARCH_INDEX = process.env.ELASTICSEARCH_INDEX
const ELASTICSEARCH_USERNAME = process.env.ELASTICSEARCH_USERNAME
const ELASTICSEARCH_PASSWORD = process.env.ELASTICSEARCH_PASSWORD

module.exports = { ELASTICSEARCH_URL, ELASTICSEARCH_INDEX, ELASTICSEARCH_USERNAME, ELASTICSEARCH_PASSWORD }